"""
LeakWatch Repository Integrity Audit
=====================================
Verifies artifacts, validates dataset/model, tests DB connectivity,
and determines the next safe workflow step.
"""

import sys
import os
import asyncio
import logging
from pathlib import Path
from types import SimpleNamespace
from datetime import datetime

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
os.chdir(PROJECT_ROOT)

import pandas as pd
import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger("repo_audit")

# Accumulate results
report = {}

# ═══════════════════════════════════════════════════════════════════
# STEP 1 — Repository Integrity Audit
# ═══════════════════════════════════════════════════════════════════
def step1_repository_audit():
    print("\n" + "=" * 70)
    print("STEP 1 — Repository Integrity Audit")
    print("=" * 70)

    target_files = {
        "data/synthetic/payments_6500_rows.csv": "Raw synthetic dataset with 6500 rows and injected anomalies (duplicates, vendor anomalies, spikes). Generated by generate_synthetic_payments.py.",
        "data/processed/payments_6500_rows_clean.csv": "Cleaned synthetic dataset — dates parsed, numeric amounts, extra columns removed, YEAR/MONTH added. Produced by e2e_pipeline_validation.py Step 1.",
        "models/isolation_forest.pkl": "Trained Isolation Forest anomaly detection model. Trained in-memory by e2e_pipeline_validation.py on the 6500-row cleaned dataset.",
        "scripts/analyze_synthetic_dataset.py": "Standalone dataset analysis script — computes statistics, detects duplicates, vendor anomalies, keyword flags, department spikes.",
        "scripts/validate_pipeline.py": "Expected validation script (may not exist).",
    }

    file_audit = {}
    print(f"\n{'File':<55} {'Exists':<10} {'Size':<12}")
    print("-" * 77)

    for fpath, purpose in target_files.items():
        p = Path(fpath)
        exists = p.exists()
        size = f"{p.stat().st_size:,} B" if exists else "—"
        status = "YES" if exists else "NO"
        print(f"  {fpath:<53} {status:<10} {size:<12}")
        file_audit[fpath] = {"exists": exists, "purpose": purpose}

    # Check for duplicate / redundant scripts
    print("\n--- Duplicate / Redundant Script Analysis ---")

    scripts_dir = Path("scripts")
    all_scripts = sorted(scripts_dir.glob("*.py")) + sorted(scripts_dir.glob("*.sh"))
    print(f"\nAll files in scripts/:")
    for s in all_scripts:
        sz = s.stat().st_size
        print(f"  {s.name:<45} {sz:>8,} B")

    # Identify overlapping functionality
    overlaps = []

    e2e_val = Path("scripts/e2e_pipeline_validation.py")
    e2e_exec = Path("scripts/run_e2e_execution.py")
    if e2e_val.exists() and e2e_exec.exists():
        overlaps.append({
            "files": ["scripts/e2e_pipeline_validation.py", "scripts/run_e2e_execution.py"],
            "overlap": "Both perform end-to-end pipeline execution including dataset cleaning, ML scoring, and DB operations.",
            "recommendation": "KEEP BOTH — they serve different purposes. e2e_pipeline_validation.py is the offline-safe validator with DB fallback. run_e2e_execution.py is the full DB-dependent execution script. No conflict.",
        })

    analyze = Path("scripts/analyze_synthetic_dataset.py")
    if analyze.exists() and e2e_val.exists():
        overlaps.append({
            "files": ["scripts/analyze_synthetic_dataset.py", "scripts/e2e_pipeline_validation.py (Step 2)"],
            "overlap": "Both perform dataset analysis (duplicates, vendor anomalies, department spikes).",
            "recommendation": "KEEP BOTH — analyze_synthetic_dataset.py is a standalone analysis tool; e2e_pipeline_validation.py embeds analysis as part of the larger validation flow. No conflict.",
        })

    # Check for the two cleaned CSVs
    cleaned_1 = Path("data/processed/payments_cleaned.csv")
    cleaned_2 = Path("data/processed/payments_6500_rows_clean.csv")
    if cleaned_1.exists() and cleaned_2.exists():
        overlaps.append({
            "files": ["data/processed/payments_cleaned.csv", "data/processed/payments_6500_rows_clean.csv"],
            "overlap": "Two cleaned datasets in processed/. payments_cleaned.csv is from clean_data.py (raw data). payments_6500_rows_clean.csv is from e2e_pipeline_validation.py (synthetic data).",
            "recommendation": "KEEP BOTH — different source data. payments_cleaned.csv = cleaned raw historical. payments_6500_rows_clean.csv = cleaned synthetic for validation. Ensure ml_pipeline.py and the app code reference the correct one.",
        })

    if overlaps:
        for i, o in enumerate(overlaps, 1):
            print(f"\n  Overlap #{i}:")
            print(f"    Files:          {', '.join(o['files'])}")
            print(f"    Nature:         {o['overlap']}")
            print(f"    Recommendation: {o['recommendation']}")
    else:
        print("  No conflicting artifacts detected.")

    # validate_pipeline.py check
    vp = Path("scripts/validate_pipeline.py")
    if not vp.exists():
        print(f"\n  NOTE: scripts/validate_pipeline.py does NOT exist.")
        print(f"        This file was never created. Its intended role is covered")
        print(f"        by scripts/e2e_pipeline_validation.py.")

    report["repository_audit"] = {
        "files": file_audit,
        "overlaps": len(overlaps),
        "conflicts": 0,
        "validate_pipeline_exists": vp.exists(),
    }
    return file_audit


# ═══════════════════════════════════════════════════════════════════
# STEP 2 — Dataset Validation Confirmation
# ═══════════════════════════════════════════════════════════════════
def step2_dataset_validation():
    print("\n" + "=" * 70)
    print("STEP 2 — Dataset Validation Confirmation")
    print("=" * 70)

    clean_path = Path("data/processed/payments_6500_rows_clean.csv")
    if not clean_path.exists():
        print("ERROR: Cleaned dataset not found!")
        report["dataset_validation"] = {"status": "FAIL", "reason": "file not found"}
        return None

    df = pd.read_csv(str(clean_path))

    # Column validation
    expected_cols = {"VOUCHER NUMBER", "AMOUNT", "CHECK DATE", "DEPARTMENT NAME", "VENDOR NAME"}
    actual_cols = set(df.columns)
    missing = expected_cols - actual_cols
    extra = actual_cols - expected_cols - {"YEAR", "MONTH"}

    print("\n--- Column Validation ---")
    print(f"  Expected:  {sorted(expected_cols)}")
    print(f"  Actual:    {sorted(df.columns.tolist())}")
    print(f"  Missing:   {sorted(missing) if missing else 'none'}")
    print(f"  Extra:     {sorted(extra) if extra else 'none (YEAR/MONTH are expected additions)'}")
    cols_ok = len(missing) == 0

    # Numeric amount parsing
    print("\n--- Amount Parsing ---")
    df["AMOUNT"] = pd.to_numeric(df["AMOUNT"], errors="coerce")
    null_amounts = df["AMOUNT"].isna().sum()
    print(f"  Dtype:       {df['AMOUNT'].dtype}")
    print(f"  Null values: {null_amounts}")
    amounts_ok = null_amounts == 0 and pd.api.types.is_numeric_dtype(df["AMOUNT"])

    # Datetime parsing
    print("\n--- Date Parsing ---")
    df["CHECK DATE"] = pd.to_datetime(df["CHECK DATE"], errors="coerce")
    null_dates = df["CHECK DATE"].isna().sum()
    print(f"  Dtype:       {df['CHECK DATE'].dtype}")
    print(f"  Null values: {null_dates}")
    dates_ok = null_dates == 0

    # Vendor name presence
    print("\n--- Vendor Name ---")
    null_vendors = df["VENDOR NAME"].isna().sum()
    print(f"  Null values: {null_vendors}")
    vendors_ok = null_vendors == 0

    # Voucher uniqueness
    print("\n--- Voucher Number Uniqueness ---")
    voucher_dupes = df["VOUCHER NUMBER"].duplicated().sum()
    print(f"  Duplicates:  {voucher_dupes}")
    vouchers_ok = voucher_dupes == 0

    # Dataset statistics
    print("\n--- Dataset Statistics ---")
    total = len(df)
    unique_vendors = df["VENDOR NAME"].nunique()
    unique_depts = df["DEPARTMENT NAME"].nunique()
    date_min = df["CHECK DATE"].min()
    date_max = df["CHECK DATE"].max()
    amt_min = df["AMOUNT"].min()
    amt_max = df["AMOUNT"].max()
    amt_mean = df["AMOUNT"].mean()
    amt_median = df["AMOUNT"].median()

    print(f"  Total rows:         {total:,}")
    print(f"  Unique vendors:     {unique_vendors}")
    print(f"  Unique departments: {unique_depts}")
    print(f"  Date range:         {date_min} to {date_max}")
    print(f"  Amount min:         ${amt_min:,.2f}")
    print(f"  Amount max:         ${amt_max:,.2f}")
    print(f"  Amount mean:        ${amt_mean:,.2f}")
    print(f"  Amount median:      ${amt_median:,.2f}")

    all_ok = cols_ok and amounts_ok and dates_ok and vendors_ok and vouchers_ok
    status = "VALID" if all_ok else "INVALID"
    print(f"\n  Dataset validation: {status}")

    report["dataset_validation"] = {
        "status": status,
        "total_rows": total,
        "unique_vendors": unique_vendors,
        "unique_departments": unique_depts,
        "date_range": f"{date_min} to {date_max}",
        "amount_min": float(amt_min),
        "amount_max": float(amt_max),
        "amount_mean": float(amt_mean),
        "amount_median": float(amt_median),
        "columns_ok": cols_ok,
        "amounts_ok": amounts_ok,
        "dates_ok": dates_ok,
        "vendors_ok": vendors_ok,
        "vouchers_unique": vouchers_ok,
    }
    return df


# ═══════════════════════════════════════════════════════════════════
# STEP 3 — ML Model Validation
# ═══════════════════════════════════════════════════════════════════
def step3_model_validation(df):
    print("\n" + "=" * 70)
    print("STEP 3 — ML Model Validation")
    print("=" * 70)

    model_path = Path("models/isolation_forest.pkl")
    if not model_path.exists():
        print(f"ERROR: Model file not found at {model_path}")
        report["model_validation"] = {"status": "FAIL", "reason": "file not found"}
        return False

    print(f"  Model file: {model_path} ({model_path.stat().st_size:,} bytes)")

    # Load via project's model loader
    print("\n--- Loading via app.ml.model_loader ---")
    try:
        from app.ml.model_loader import get_model
        model = get_model()
        print(f"  Model loaded: OK")
        print(f"  Model type:   {type(model).__name__}")
        print(f"  Inner model:  {type(model.model).__name__}")
    except Exception as e:
        print(f"  Model loading FAILED: {e}")
        report["model_validation"] = {"status": "FAIL", "reason": str(e)}
        return False

    # Score sample transactions via scoring_engine
    print("\n--- Scoring Sample Transactions ---")
    from app.ml.feature_engineering import extract_transaction_features

    dept_stats = df.groupby("DEPARTMENT NAME")["AMOUNT"].agg(["mean", "std"]).to_dict("index")
    sample = df.sample(n=min(5, len(df)), random_state=42)

    results = []
    for _, row in sample.iterrows():
        txn = SimpleNamespace(
            voucher_number=row["VOUCHER NUMBER"],
            amount=float(row["AMOUNT"]),
            check_date=row["CHECK DATE"],
            department=row["DEPARTMENT NAME"],
            description="",
            vendor_name=row["VENDOR NAME"],
        )
        d = dept_stats.get(row["DEPARTMENT NAME"], {"mean": 0, "std": 0})
        features = extract_transaction_features(
            txn,
            recent_transaction_count=0,
            department_avg_amount=float(d["mean"]),
            department_std_amount=float(d["std"]) if not pd.isna(d["std"]) else 0.0,
        )
        score = model.score(features)

        risk_factors = []
        if features["is_large_transaction"]:
            risk_factors.append("large_transaction")
        if features["is_procurement"]:
            risk_factors.append("procurement_department")
        if abs(features["amount_zscore"]) > 3:
            risk_factors.append("department_spending_outlier")

        results.append({
            "voucher_number": row["VOUCHER NUMBER"],
            "leak_probability": score,
            "risk_factors": risk_factors,
        })

    print(f"\n  {'Voucher Number':<22} {'Leak Prob':>10}  Risk Factors")
    print("  " + "-" * 65)
    for r in results:
        factors = ", ".join(r["risk_factors"]) if r["risk_factors"] else "none"
        print(f"  {r['voucher_number']:<22} {r['leak_probability']:>10.4f}  {factors}")

    scoring_ok = all(0.0 <= r["leak_probability"] <= 1.0 for r in results)
    print(f"\n  Model scoring: {'OK' if scoring_ok else 'FAIL'}")
    print(f"  All scores in [0, 1]: {'YES' if scoring_ok else 'NO'}")

    report["model_validation"] = {
        "status": "OK" if scoring_ok else "FAIL",
        "model_loaded": True,
        "scoring_valid": scoring_ok,
        "sample_count": len(results),
    }
    return scoring_ok


# ═══════════════════════════════════════════════════════════════════
# STEP 4 — Database Connectivity Check
# ═══════════════════════════════════════════════════════════════════
async def step4_db_check():
    print("\n" + "=" * 70)
    print("STEP 4 — Database Connectivity Check")
    print("=" * 70)

    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass

    db_url = os.environ.get("DATABASE_URL", "")
    if not db_url:
        print("  DATABASE_URL not set — connection unavailable")
        report["database_status"] = "UNAVAILABLE (no DATABASE_URL)"
        return False

    # Mask the URL for printing
    if "@" in db_url:
        host_part = db_url.split("@")[1].split("/")[0]
        print(f"  Target host: {host_part}")
    print(f"  Attempting connection (5-second timeout)...")

    try:
        import asyncpg
        conn = await asyncio.wait_for(
            asyncpg.connect(dsn=db_url),
            timeout=5.0,
        )
        version = await conn.fetchval("SELECT version()")
        now = await conn.fetchval("SELECT now()")
        await conn.close()
        print(f"  DATABASE CONNECTION: SUCCESS")
        print(f"  Server version: {str(version)[:80]}")
        print(f"  Server time:    {now}")
        report["database_status"] = "SUCCESS"
        return True

    except asyncio.TimeoutError:
        print(f"  DATABASE CONNECTION: UNAVAILABLE (timeout after 5 seconds)")
        report["database_status"] = "UNAVAILABLE (timeout)"
        return False
    except Exception as e:
        print(f"  DATABASE CONNECTION: UNAVAILABLE ({type(e).__name__}: {e})")
        report["database_status"] = f"UNAVAILABLE ({type(e).__name__})"
        return False


# ═══════════════════════════════════════════════════════════════════
# STEP 5 — Determine Next Safe Step
# ═══════════════════════════════════════════════════════════════════
def step5_next_step(db_connected, dataset_ok, model_ok):
    print("\n" + "=" * 70)
    print("STEP 5 — Next Safe Step Determination")
    print("=" * 70)

    if not dataset_ok:
        next_step = "Fix dataset issues before proceeding."
        print(f"  Dataset validation failed — cannot proceed.")
    elif not model_ok:
        next_step = "Fix or retrain the ML model before proceeding."
        print(f"  Model validation failed — cannot proceed.")
    elif not db_connected:
        # Case A — Database unavailable
        print(f"  All offline pipeline components are verified and working:")
        print(f"    - Cleaned dataset:   VALID")
        print(f"    - ML model:          LOADED and SCORING")
        print(f"    - Feature pipeline:  OPERATIONAL")
        print(f"    - Database:          UNAVAILABLE")
        print()
        print(f"  The system is ready for full pipeline execution once")
        print(f"  database connectivity is restored.")
        next_step = "NEXT STEP: Fix database connectivity and run the first full pipeline execution."
    else:
        # Case B — Database available
        print(f"  All components operational:")
        print(f"    - Cleaned dataset:   VALID")
        print(f"    - ML model:          LOADED and SCORING")
        print(f"    - Database:          CONNECTED")
        print()
        print(f"  Ready to execute full pipeline:")
        print(f"    1. Insert cleaned dataset into transactions table")
        print(f"    2. POST /api/v1/ml/run-analysis")
        print(f"    3. Monitor run status via GET /api/v1/ml/run-status/{{run_id}}")
        print(f"    4. Validate analysis tables")
        print(f"    5. Test dashboard API endpoints")
        next_step = "NEXT STEP: Run full pipeline execution (insert data → ML analysis → dashboard validation)."

    print(f"\n  {next_step}")
    report["next_step"] = next_step
    return next_step


# ═══════════════════════════════════════════════════════════════════
# STEP 6 — Final Status Report
# ═══════════════════════════════════════════════════════════════════
def step6_final_report():
    print("\n" + "=" * 70)
    print("STEP 6 — Final Status Report")
    print("=" * 70)

    # Repository Audit
    print("\n## REPOSITORY AUDIT")
    ra = report.get("repository_audit", {})
    files = ra.get("files", {})
    for fpath, info in files.items():
        status = "EXISTS" if info["exists"] else "MISSING"
        print(f"  [{status}] {fpath}")
        print(f"           {info['purpose'][:90]}")
    print(f"\n  Overlapping artifacts:  {ra.get('overlaps', 'N/A')} (non-conflicting)")
    print(f"  Conflicting artifacts: {ra.get('conflicts', 0)}")
    vp = ra.get("validate_pipeline_exists", False)
    print(f"  validate_pipeline.py:  {'EXISTS' if vp else 'DOES NOT EXIST (covered by e2e_pipeline_validation.py)'}")

    # Dataset Validation
    print("\n## DATASET VALIDATION")
    dv = report.get("dataset_validation", {})
    print(f"  Status:             {dv.get('status', 'N/A')}")
    print(f"  Total rows:         {dv.get('total_rows', 'N/A'):,}")
    print(f"  Unique vendors:     {dv.get('unique_vendors', 'N/A')}")
    print(f"  Unique departments: {dv.get('unique_departments', 'N/A')}")
    print(f"  Date range:         {dv.get('date_range', 'N/A')}")
    print(f"  Amount min:         ${dv.get('amount_min', 0):,.2f}")
    print(f"  Amount max:         ${dv.get('amount_max', 0):,.2f}")
    print(f"  Amount mean:        ${dv.get('amount_mean', 0):,.2f}")
    print(f"  Amount median:      ${dv.get('amount_median', 0):,.2f}")
    print(f"  Columns OK:         {dv.get('columns_ok', 'N/A')}")
    print(f"  Amounts OK:         {dv.get('amounts_ok', 'N/A')}")
    print(f"  Dates OK:           {dv.get('dates_ok', 'N/A')}")
    print(f"  Vendors OK:         {dv.get('vendors_ok', 'N/A')}")
    print(f"  Vouchers unique:    {dv.get('vouchers_unique', 'N/A')}")

    # Model Validation
    print("\n## MODEL VALIDATION")
    mv = report.get("model_validation", {})
    print(f"  Status:         {mv.get('status', 'N/A')}")
    print(f"  Model loaded:   {mv.get('model_loaded', 'N/A')}")
    print(f"  Scoring valid:  {mv.get('scoring_valid', 'N/A')}")

    # Database Status
    print("\n## DATABASE STATUS")
    print(f"  {report.get('database_status', 'N/A')}")

    # Next Step
    print("\n## NEXT STEP")
    print(f"  {report.get('next_step', 'N/A')}")

    print("\n" + "=" * 70)


# ═══════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════
async def main():
    print("=" * 70)
    print("  LeakWatch Repository Integrity Audit")
    print(f"  Executed: {datetime.now().isoformat()}")
    print("=" * 70)

    # Step 1
    step1_repository_audit()

    # Step 2
    df = step2_dataset_validation()
    dataset_ok = df is not None and report.get("dataset_validation", {}).get("status") == "VALID"

    # Step 3
    model_ok = False
    if dataset_ok:
        model_ok = step3_model_validation(df)

    # Step 4
    db_connected = await step4_db_check()

    # Step 5
    step5_next_step(db_connected, dataset_ok, model_ok)

    # Step 6
    step6_final_report()


if __name__ == "__main__":
    asyncio.run(main())
